### ISSUE TITLE
creating a container from a public hub image requires login infos and fails

### ISSUE THREAD

**Issue by azazel75** [ansible/docker#2]
Scenario: the user running the docker command doesn't have any login infos saved into ~/.docker/config.json for the docker hub.

A play runs the following tasks

``` yaml
    - name:
      docker_container:
        image: 'debian:jessie'
        name: foo
        state: started
        command:
          - sleep
          - infinity
      register: output
      ignore_errors: yes

    - debug: var=output
```

The ansible-playbook command will print this output

```
PLAY [example.com] ****************************************************

TASK [None] ********************************************************************
fatal: [example.com]: FAILED! => {"changed": false, "failed": true, "msg": "Error: configuration for docker.io not found. Try logging into docker.io first."}
...ignoring

TASK [debug] *******************************************************************
ok: [example.com] => {
    "output": {
        "changed": false, 
        "failed": true, 
        "msg": "Error: configuration for docker.io not found. Try logging into docker.io first."
    }
}

PLAY RECAP *********************************************************************
example.com       : ok=2    changed=0    unreachable=0    failed=0 
```

It really shouldn't fail if no login is required to pull the image.

As an added problem, this very image (debian:jessie) was already downloaded and it should have not triggered any pull. I tried to circumnvent this by adding "pull: no" but the result is the same.
